### ISSUE TITLE
Not able to run 'test.py' easily.

### ISSUE THREAD

**Issue by QuantumLiu** [huangzhikun1995/IPM-Net#3]
Thank you for your great work.
But I've got several errors when I started trying to run 'test.py', I hope it may help you to make the repo even better:
Firts:
```
Traceback (most recent call last):
  File "test.py", line 4, in <module>
    from trainer import IPMNet_Trainer
  File "C:\pyprojects\IPM-Net\trainer.py", line 234
    '''
      ^
SyntaxError: EOF while scanning triple-quoted string literal
```
I edited the file and fixed it.
Second:
```
Traceback (most recent call last):
  File "test.py", line 22, in <module>
    assert 0, "please changse the name to your model name"
AssertionError: please changse the name to your model name

```
It caused by that there is no folder named 'outputs' in the repo, I downloaded the folder from the Cloud Drive. But I stiil can't figure out where to put 'resnet50_ft_weight.pkl' after reading README.
Third, in test.py pathes are Linux absolute pathes, such as :'/home/username/IPM-Net/datasets/'. Maybe relative pathes are better.

**Comment by huangzhikun1995** [comment]
Thank you for your valuable advice. And I hope my reply will help you.

1.     Due to my negligence, there was a slight error in 'trainer.py’. Thank you for reminding me.

2.     The folder ‘outputs’ should be created in “~/IPM-Net/”, and It is used to store training results.

3.     ‘resnet50_ft_weight.pkl’ should be moved to “~/IPM-Net/”.
